version: '3'
services:
  receitas-database:
    image: postgres:17
    container_name: receitas-database
    environment:
      POSTGRES_DB: receitas
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - refeicoes-network

  receitas-cache:
    image: redis:7
    container_name: receitas-cache
    ports:
      - "6379:6379"
    networks:
      - refeicoes-network

  api-receitas:
    build:
      context: .
    container_name: receitas-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://receitas-database:5432/receitas
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - refeicoes-network
    depends_on:
      - receitas-database
      - receitas-cache

networks:
  refeicoes-network:
    external: true

